language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  matrix:
    - PLONE_VERSION=4.3.x
    - PLONE_VERSION=5.0.x
    - PLONE_VERSION=5.1.x
python:
  - 2.7
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - sed -ie "s#buildout.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls

notifications:
  email:
    - info@kitconcept.com
