language: python
python:
  - "2.7"
  - "3.7"
dist: xenial
sudo: required
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=4.3.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install cookiecutter
  - pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - buildout -t 10 -c travis.cfg
script:
  - make code-analysis
  - make test-release
  - make test
